//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yarisma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karakter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karakter()
        {
            this.Kullanicis = new HashSet<Kullanici>();
        }
    
        public int karakterId { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> yasamSuresi { get; set; }
        public Nullable<int> harcananSure { get; set; }
        public Nullable<int> dogruSayisi { get; set; }
        public Nullable<int> toplamSoruSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
    }
}
