//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yarisma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullaniciId { get; set; }
        public string sifre { get; set; }
        public string kullaniciAdi { get; set; }
        public string email { get; set; }
        public Nullable<int> durum { get; set; }
        public Nullable<int> karakterId { get; set; }
    
        public virtual Karakter Karakter { get; set; }
    }
}
