//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yarisma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public int soruId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string cevap { get; set; }
        public string soruIcerik { get; set; }
        public string secenekA { get; set; }
        public string secenekB { get; set; }
        public string secenekC { get; set; }
        public string secenekD { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
